name: Build Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'feature-probe-docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'feature-probe-docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: feature-probe-docs/

    - name: Install dependencies
      run: npm ci
      working-directory: ./feature-probe-docs/

      
    - name: Build website
      run: npm run build
      working-directory: ./feature-probe-docs/
      
  deploy:
      needs: build
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      permissions:
        id-token: write
        contents: read
      steps:
        - id: 'auth'
          name: 'Authenticate to Google Cloud'
          uses: 'google-github-actions/auth@v0.3.1'
          with:
            create_credentials_file: true
            workload_identity_provider: 'projects/363590592857/locations/global/workloadIdentityPools/github-action/providers/github'
            service_account: '363590592857-compute@developer.gserviceaccount.com'
          
          
        - id: 'gcloud'
          name: 'run gcloud'
          run: |-
            gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
            gcloud config set project tranquil-post-357802 
            gcloud compute ssh featureprobe --zone=asia-east1-a --command="echo '★★★★★★★★★★★★★★★★[Start Deploy instance featureprobe]★★★★★★★★★★★★★★★★';wget --header 'Authorization: token ${{ secrets.GH_API_TOKEN }}' https://raw.githubusercontent.com/FeatureProbe/internal_script/main/io/deploy-docs.sh -O deploy-docs.sh;sudo chmod +x deploy-docs.sh;sudo ./deploy-docs.sh"
