name: Build Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'feature-probe-docs/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'feature-probe-docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read
        
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
        cache-dependency-path: feature-probe-docs/

    - name: Install dependencies
      run: npm ci
      working-directory: ./feature-probe-docs/

      
    - name: Build website
      run: npm run build
      working-directory: ./feature-probe-docs/
      
    - name: pack website tarball
      run: tar -czvf ./feature-probe-docs/docs.tar.gz ./feature-probe-docs/build


    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
        create_credentials_file: true
        workload_identity_provider: 'projects/363590592857/locations/global/workloadIdentityPools/github-action/providers/github'
        service_account: '363590592857-compute@developer.gserviceaccount.com'


    - id: 'gcloud'
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      name: 'upload to gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud config set project tranquil-post-357802 
        gcloud compute scp ./feature-probe-docs/docs.tar.gz  featureprobe:/home/ --zone=asia-east1-a
        
