name: Deploy to Google Cloud

on:
  workflow_dispatch:
  
  workflow_call:

jobs:
  deployment:
    environment: trial
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/363590592857/locations/global/workloadIdentityPools/github-action/providers/github'
          service_account: '363590592857-compute@developer.gserviceaccount.com'
          project_id: tranquil-post-357802
          
          
      - id: 'gcloud'
        name: 'gcloud'
        shell: bash
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud config set project tranquil-post-357802 
          gcloud compute ssh featureprobe --zone=asia-east1-a --command="set -eo pipefail;echo '★★★★★★★★★★★★★★★★[Start Deploy instance featureprobe]★★★★★★★★★★★★★★★★';wget --header 'Authorization: token ${{ secrets.GH_API_TOKEN }}' https://raw.githubusercontent.com/FeatureProbe/internal_script/main/io/start.sh -O start.sh;sudo chmod +x start.sh;sudo ./start.sh"
          gcloud compute ssh featureprobe-db --zone=asia-east1-a --command="set -eo pipefail;echo '★★★★★★★★★★★★★★★★[Start Deploy instance featureprobe-db]★★★★★★★★★★★★★★★★';wget --header 'Authorization: token ${{ secrets.GH_API_TOKEN }}' https://raw.githubusercontent.com/FeatureProbe/internal_script/main/io/start.sh -O start.sh;sudo chmod +x start.sh;sudo ./start.sh"
