name: Publish Docker Image when Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        default: 'alpha'
        type: string

permissions:
  contents: read
  
jobs:
  release_api:
    name: Release API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file ./feature-probe-api/pom.xml
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
            
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Docker Build API (by release)
        if: ${{ github.event_name == 'release' }}
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag featureprobe/api:${GITHUB_REF#refs/tags/} \
            --tag featureprobe/api:latest \
            --file ./Dockerfile ./
        working-directory: ./feature-probe-api
    
      - name: Docker Build API (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag featureprobe/api:$DOCKER_TAG \
            --tag featureprobe/api:latest \
            --file ./Dockerfile ./
        env:
          DOCKER_TAG: ${{ inputs.tag }}
        working-directory: ./feature-probe-api
      - name: Inspect image
        run: |
          docker buildx imagetools inspect featureprobe/api
        working-directory: ./feature-probe-api
  
  release_ui:
    name: Release UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
            
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Docker Build UI (by release)
        if: ${{ github.event_name == 'release' }}
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag featureprobe/ui:latest \
            --tag featureprobe/ui:${GITHUB_REF#refs/tags/} \
            --file ./Dockerfile ./
        working-directory: ./feature-probe-ui    
  
      - name: Docker Build UI (manually)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag featureprobe/ui:latest \
            --tag featureprobe/ui:$DOCKER_TAG \
            --file ./Dockerfile ./
        env:
          DOCKER_TAG: ${{ inputs.tag }}
        working-directory: ./feature-probe-ui    
        
      - name: Inspect image
        run: |
          docker buildx imagetools inspect featureprobe/ui
        working-directory: ./feature-probe-ui  
