# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: UI Build & Test

on:
  push:
    branches: [ main ]
    paths:
      - 'feature-probe-ui/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'feature-probe-ui/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: yarn install
      run: yarn install --frozen-lockfile
      working-directory: ./feature-probe-ui
      
    - name: yarn build
      run: yarn build
      working-directory: ./feature-probe-ui
      
    - name: unit test
      run: yarn test:cov
      working-directory: ./feature-probe-ui
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3

    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
   
    - name: Docker Buildx (push)
      run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag featureprobe/ui:latest \
            --file ./Dockerfile ./
          working-directory: ./feature-probe-ui    
   
    - name: Inspect image
      run: |
          docker buildx imagetools inspect featureprobe/ui
      working-directory: ./feature-probe-ui  
